import{a as q,S,i as r}from"./assets/vendor-CRsTpldL.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function i(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=i(o);fetch(o.href,s)}})();const R="51577392-fe6fcec4f7e04f8f3d5104f81",M="https://pixabay.com/api/";async function h(e,t){const i={key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:t};return(await q.get(M,{params:i})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".show-more-btn"),E=new S(".gallery .gallery-link",{captions:!0,captionsData:"alt",captionDelay:250,scrollZoom:!1});function y(e){const t=$(e);f.insertAdjacentHTML("beforeend",t),E.refresh()}function P(){f.innerHTML=""}function L(){m.classList.add("is-visible")}function w(){m.classList.remove("is-visible")}function B(){g.classList.add("js-show-more")}function a(){g.classList.remove("js-show-more")}function T(e){return`<li class="image-item">
        <a class='gallery-link' href='${e.largeImageURL}'>
            <img src="${e.webformatURL}" alt="${e.tags.split(",").slice(0,3).join(",")}" class='image'/>
        </a>
        <div class="image-info">
          <p><span class='title'>Likes:</span><span class='counts'>${e.likes}</span></p>
          <p><span class='title'>Views:</span><span class='counts'>${e.views}</span></p>
          <p><span class='title'>Comments:</span><span class='counts'>${e.comments}</span></p>
          <p><span class='title'>Downloads:</span><span class='counts'>${e.downloads}</span></p>
        </div>
      </li>`}function $(e){return e.map(T).join("")}const d=document.querySelector(".form"),O=document.querySelector(".show-more-btn"),u=document.querySelector(".scroll-to-top");let n=1,p=0;const v=15;let b="";d.addEventListener("submit",e=>{e.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){r.error({message:"Please enter a search query",position:"topRight"});return}b=t,n=1,j(t)});O.addEventListener("click",()=>{L(),h(b,n).then(e=>{if(e.hits.length===0){r.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a();return}y(e.hits),n++;const t=document.querySelector(".gallery .image-item");if(t){const i=t.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}n>Math.ceil(p/v)&&(a(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(()=>{r.error({message:"Error loading images",position:"topRight"})}).finally(()=>{w()})});function j(e){P(),a(),L(),h(e,n).then(t=>{if(t.hits.length===0){r.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a();return}p=t.totalHits,y(t.hits),n++,n>Math.ceil(p/v)?(a(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):B()}).catch(()=>{r.error({message:"Error loading images",position:"topRight"})}).finally(()=>{w()})}window.addEventListener("scroll",()=>{window.scrollY>400?u.style.display="block":u.style.display="none"});u.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
