import{a as S,S as R,i as r}from"./assets/vendor-CRsTpldL.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))c(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function i(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(s){if(s.ep)return;s.ep=!0;const o=i(s);fetch(s.href,o)}})();const M="51577392-fe6fcec4f7e04f8f3d5104f81",E="https://pixabay.com/api/";async function m(e,t){const i={key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:t};return(await S.get(E,{params:i})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".show-more-btn"),P=new R(".gallery .gallery-link",{captions:!0,captionsData:"alt",captionDelay:250,scrollZoom:!1});function y(e){const t=$(e);f.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){f.innerHTML=""}function w(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}function v(){g.classList.add("js-show-more")}function n(){g.classList.remove("js-show-more")}function T(e){return`<li class="image-item">
        <a class='gallery-link' href='${e.largeImageURL}'>
            <img src="${e.webformatURL}" alt="${e.tags.split(",").slice(0,3).join(",")}" class='image'/>
        </a>
        <div class="image-info">
          <p><span class='title'>Likes:</span><span class='counts'>${e.likes}</span></p>
          <p><span class='title'>Views:</span><span class='counts'>${e.views}</span></p>
          <p><span class='title'>Comments:</span><span class='counts'>${e.comments}</span></p>
          <p><span class='title'>Downloads:</span><span class='counts'>${e.downloads}</span></p>
        </div>
      </li>`}function $(e){return e.map(T).join("")}const d=document.querySelector(".form"),O=document.querySelector(".show-more-btn"),u=document.querySelector(".scroll-to-top");let a=1,p=0;const b=15;let q="";d.addEventListener("submit",async e=>{e.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){r.error({message:"Please enter a search query",position:"topRight"});return}q=t,a=1,await j(t)});O.addEventListener("click",async()=>{n(),w(),a++;try{const e=await m(q,a);if(e.hits.length===0){r.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n();return}y(e.hits),v();const t=document.querySelector(".image-item");if(t){const i=t.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}a>Math.ceil(p/b)&&(n(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{r.error({message:"Error loading images",position:"topRight"})}finally{L()}});async function j(e){B(),n(),w();try{const t=await m(e,a);if(t.hits.length===0){r.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n();return}p=t.totalHits,y(t.hits),a>Math.ceil(p/b)?(n(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{r.error({message:"Error loading images",position:"topRight"})}finally{L()}}window.addEventListener("scroll",()=>{window.scrollY>400?u.style.display="block":u.style.display="none"});u.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
