import{a as S,S as R,i as r}from"./assets/vendor-CRsTpldL.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=a(o);fetch(o.href,s)}})();const M="51577392-fe6fcec4f7e04f8f3d5104f81",E="https://pixabay.com/api/";async function h(e,t){const a={key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:t};return(await S.get(E,{params:a})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".show-more-btn"),P=new R(".gallery .gallery-link",{captions:!0,captionsData:"alt",captionDelay:250,scrollZoom:!1});function y(e){const t=$(e);f.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){f.innerHTML=""}function L(){m.classList.add("is-visible")}function w(){m.classList.remove("is-visible")}function v(){g.classList.add("js-show-more")}function i(){g.classList.remove("js-show-more")}function T(e){return`<li class="image-item">
        <a class='gallery-link' href='${e.largeImageURL}'>
            <img src="${e.webformatURL}" alt="${e.tags.split(",").slice(0,3).join(",")}" class='image'/>
        </a>
        <div class="image-info">
          <p><span class='title'>Likes:</span><span class='counts'>${e.likes}</span></p>
          <p><span class='title'>Views:</span><span class='counts'>${e.views}</span></p>
          <p><span class='title'>Comments:</span><span class='counts'>${e.comments}</span></p>
          <p><span class='title'>Downloads:</span><span class='counts'>${e.downloads}</span></p>
        </div>
      </li>`}function $(e){return e.map(T).join("")}const d=document.querySelector(".form"),O=document.querySelector(".show-more-btn"),u=document.querySelector(".scroll-to-top");let n=1,p=0;const b=15;let q="";d.addEventListener("submit",e=>{e.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){r.error({message:"Please enter a search query",position:"topRight"});return}q=t,n=1,j(t)});O.addEventListener("click",()=>{i(),L(),h(q,n).then(e=>{if(e.hits.length===0){r.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),i();return}y(e.hits),v(),n++;const t=document.querySelector(".gallery .image-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}n>Math.ceil(p/b)&&(i(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(()=>{r.error({message:"Error loading images",position:"topRight"})}).finally(()=>{w()})});function j(e){B(),i(),L(),h(e,n).then(t=>{if(t.hits.length===0){r.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();return}p=t.totalHits,y(t.hits),n++,n>Math.ceil(p/b)?(i(),r.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}).catch(()=>{r.error({message:"Error loading images",position:"topRight"})}).finally(()=>{w()})}window.addEventListener("scroll",()=>{window.scrollY>400?u.style.display="block":u.style.display="none"});u.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
